#! /bin/bash

[[ -n $DEBUG ]] && set -x

set -eou pipefail

readonly SCRIPT_DIR="$(dirname $0)"
readonly NOTES_DIR=${NOTES_DIR:-"$(dirname $0)/.notes"}
readonly LOGS_FILE="$SCRIPT_DIR/.log"
readonly NEXT_ID_FILE="$SCRIPT_DIR/.next_id"

main() {

  # Initialize 
  if [[ ! -f "$NEXT_ID_FILE" ]]; then
    init
  fi

  # Initialize notes directory if it doesn't alread exist
  if [[ ! -d "$NOTES_DIR" ]]; then
    init_notes
  fi

  if [ "$#" -lt 1 ]; then
    usage
    exit
  elif [ "$#" -lt 2 ]; then
    if [ "$1" = "list" ]; then
      list_books
    fi
  else
    if [ "$1" = "add" ]; then
      add_note $2
    elif [ "$1" = "view" ]; then
      view_note $2
    elif [ "$1" = "list" ]; then
      list_notes $2
    elif [ "$1" = "edit" ]; then
      edit_note $2
    fi
  fi
}

init_notes() {
  mkdir -p "$NOTES_DIR"
}

init() {
  # start the log
  local 
  touch "$LOGS_FILE"
  add_log "Initialized log file $LOGS_FILE"

  # start the id count
  touch "$NEXT_ID_FILE"
  echo 0 > "$NEXT_ID_FILE"
  add_log "Initialized next_id in the file $NEXT_ID_FILE with 0"
}

add_log() {
  printf "$1\n" >> "$LOGS_FILE"
}

get_next_id() {
  echo $(cat "$NEXT_ID_FILE")
}

increment_next_id() {
  local current_next_id=$(get_next_id)
  local next_id=$((current_next_id + 1))
  echo "$next_id" > "$NEXT_ID_FILE"
  add_log "Incremented next id to $next_id"
  echo "$next_id"
}

get_note_id() {
  echo "$(whoami)-$(get_next_id)"
}

add_note() {
  local book_name="$1"
  local book_full_path="$NOTES_DIR/$book_name"
  local note_id=$(get_note_id)
  local note_name="$(whoami)-$note_id"
  local note_full_path="$book_full_path/$note_id"

  # Initialize book directory if it doesn't exist already
  if [[ ! -d "$book_full_path" ]]; then
    mkdir -p "$book_full_path"
  fi

  increment_next_id && touch "$note_full_path"
  vi "$note_full_path"
}

view_note() {
  local note_id="$1"
  local file_path=$(find "$NOTES_DIR" -name "$note_id" | awk 'NR==1{print $1}')
  cat "$file_path"
}

edit_note() {
  local note_id="$1"
  local file_path=$(find "$NOTES_DIR" -name "$note_id" | awk 'NR==1{print $1}')
  vim "$file_path"
}

list_notes() {
  local book_name="$1"
  local book_full_path="$NOTES_DIR/$book_name"
  # local file_names=$(ls "$book_full_path" | sort)
  # echo $file_names

  local output_temp_file="$(mktemp)"

  echo "ID:TITLE" > $output_temp_file
  # echo "Notes in $book_name:"
  for file in "$book_full_path"/*
  do
    local file_name=$(basename $file)
    local first_line=$(head -n 1 $file)
    echo "$file_name:$first_line" >> $output_temp_file
  done

  column -s: -t $output_temp_file
}

list_books() {
  echo "NOTEBOOKS"
  pushd $NOTES_DIR > /dev/null
  for f in *; do
    echo $f;
  done;
  popd > /dev/null
}

usage() {
  local self="note"

  cat <<EOF
Usage:
$self                 print this help menu
$self  add <book>     add a note in <book>
$self list <book>     list all notes in <book>
$self view <note_id>  view note
$self edit <note_id>  edit a note
EOF
}

main "$@"
